apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: bazarstore-prod
spec:
  selector:
    app: catalog
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001  # Assign a specific NodePort
  type: NodePort     # Change to NodePort type