all:
  children:
    jenkins:
      hosts:
        jenkins_server:
          ansible_host: "{{ jenkins_public_ip }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "{{ jenkins_ssh_key }}"
    
    eks_nodes:
      hosts:
        eks_node_1:
          ansible_host: "{{ eks_node_1_ip }}"
          ansible_user: ec2-user
          ansible_ssh_private_key_file: "{{ eks_ssh_key }}"
        eks_node_2:
          ansible_host: "{{ eks_node_2_ip }}"
          ansible_user: ec2-user
          ansible_ssh_private_key_file: "{{ eks_ssh_key }}" 