---
# Common variables for all hosts
ansible_python_interpreter: /usr/bin/python3

# Jenkins configuration
jenkins_version: "2.426.1.3"
jenkins_port: 8080
jenkins_admin_user: admin
jenkins_admin_password: "{{ jenkins_admin_password | default('YOUR_SECURE_PASSWORD') }}"

# EKS node configuration
k8s_version: "1.28"
container_runtime: containerd
docker_version: "24.0.5"

# Common packages for all hosts
common_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - gnupg
  - lsb-release
