apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: bazarstore-prod
  labels:
    environment: production
spec:
  selector:
    app: order
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30002  # Assign a specific NodePort
  type: NodePort     # Change to NodePort type